### ISSUE TITLE
Any samples？

### ISSUE THREAD

**Issue by suzhiba** [Hiroshiba/realtime-voice-conversion#2]
Hi，
    Could you show some samples？
Thanks

**Comment by hhongjiang** [comment]
Hi,
Could you show how to run this program in Linux system (like MacOS)?
Thank you!

**Comment by Hiroshiba** [comment]
@suzhiba Voice samples are at https://youtu.be/wcyFT9C_O7k?t=65 .

**Comment by Hiroshiba** [comment]
@liferjane `realtime-yukarin` is only supporting Windows, because it uses `PyAudio`.
According to my searching, `PyAudio` is supporting Linux, so you may be able to run it on Linux.
