### ISSUE TITLE
Can u introduce your thought of real-time?

### ISSUE THREAD

**Issue by CarolinGao** [Hiroshiba/realtime-voice-conversion#4]
Hi, I have a voice conversion model, I want to convert it to a realtime model.  
1. I am confused what do "start_time" and "extra_time"  in your code mean.  
2. I want to record audio from microphone , process the audio data and play the processed audio at the meanwhile. How can I design the code?
Thank u very much!

**Comment by Hiroshiba** [comment]
Sorry for the delay in replying!

1)
In this voice conversion system, the voice is separated and converted sequentially. `start_time` is the start time of the separated voice.
`extra_time` is the padding time of the voice. Increasing this value will increase the quality of the conversion, but will also increase the delay.

2)
With PyAudio, you can convert your voice in real time. See [run.py](https://github.com/Hiroshiba/realtime-yukarin/blob/a8cd36b180c93d7251327b3ca4a027d2a9f0c868/run.py) for more information.
